### ISSUE TITLE
red cornell box

### ISSUE THREAD

**Issue by tigrazone** [takiyu/glsl-renderer#1]
windows 7, mingw2, gcc 6.2
cpu amd athlon 64 x2 4200+
gpu ati radeon hd 2600 xt
when I start render with CornellBox-Original.obj I have red cornell box.
I readed file CornellBox-Original.mtl in text editor and I see materials not only red.
How to fix it? Look at screenshot http://moo.ho.ua/glsl-issue.png
Why render is so slow? I have 1-2 fps.

**Comment by takiyu** [comment]
Thanks for your report.

I think there are some problem about sending textures (`main.cpp`, line about 437).
Some material information might be missed, or only the red channel might be used.

In this program, texture size is decided statically (`main.cpp`, line 36\~39 and `simple.fs`, line 26\~29 ).
Textures should be like squares. If they are not, some information can be missed or the rendering speed can be so slow on some GPU.

Practically, the texture sizes must be 2^x, and they should be passed to the shaders dynamically.
